### ISSUE TITLE
PHP nepagauna info

### ISSUE THREAD

**Issue by bencius** [erkexzcx/lietuviska-tv#1]
Laba, viską padarau pagal instrukciją, tačiau sukurtas .php failas neatvaizduoja turinio, kas gali būt ne taip? :)

**Comment by erkexzcx** [comment]
Jau pagauna?:)

**Comment by bencius** [comment]
Pasirodo buvo php show_exec uzblokuotas, tai atsiblokavau ir viskas ok. Taip pat dasidejau LRT kulturos generavima, taciau niekaip nesugeneruoja LRT ir LRTV kanalu. Taip pat TV3 ateina be sinchronizacijos, garsas atsilieka nuo vaizdo.

**Comment by erkexzcx** [comment]
Del TV3 tai per VLC pasidaryk garsui delay lygiai 1 sekundes (tikrai eina). Ant KODI tokios problemos nera.

LNK prades rodyti kai paliksi scripta runninti ilgesniam laikui (pvz nuo tada, kaip per LNK GO rodys zinias). Sekancia diena per piet jau greiciausiai neberodys.

LRT labai daznai rasys "turinys apribotas del autoriniu teisiu" nes live nenori rodyti copyrighted filmu matyt, bet LRT as ir seip neziuriu... :D

**Comment by bencius** [comment]
Jooo, bet turiu omeny, kad man VLC neatidaro sugeneruotu LRT ir LRTV linku. Meta error.

**Comment by bencius** [comment]
![Screenshot 2019-08-30 at 21 17 25](https://user-images.githubusercontent.com/51398552/64042893-9861db80-cb6b-11e9-9d80-06f79c2251c5.png)
Va ka rodo.

**Comment by erkexzcx** [comment]
Meluoji - turi veikt :D

Jei dabar paziuret nori tai va - is savo json failo isemiau:
```
https://srautas.lrt.lt/lrt_televizija/smil:lrt_televizija.smil/playlist.m3u8?tokenhash=I87Q3WncyOyWUoApDlooGKDOSl5tZA3ZoZxsKUbhR9K_ExFZJI5Fak7mWe87PxmB-47Lc79qe8FgkAWzf-jjDA==&tokenendtime=1567189923
```

Jei ka tik pasidarei sita scripta runninti ant servo, tai atsidaryk `/opt/livetv/links.json` ir pakeisk turini i si:
```
[{"title":"TV3 HD","picture":"https://www.telia.lt/documents/20184/3686852/tv3-on-white.png","url":"https://cdn7.tvplayhome.lt/live/eds/TV3_LT_HD/HLS_encr/TV3_LT_HD.m3u8"},{"title":"INFO TV HD","picture":"https://www.telia.lt/documents/20184/3686852/INFO-LOGO-HD.png","url":"https://live.lnk.lt/lnk_live/tiesiogiai/playlist.m3u8?tokenstarttime=0\u0026tokenendtime=1567232101\u0026tokenhash=D6OCJ28HLQV6KXxoKzsL9VnIHqR6x7hi_bL32t_ChcE7XmrGodnSEMw2M_OwWi61S0iN_Io8nUV-HdzJHSpWTQ=="},{"title":"LNK HD","picture":"https://www.telia.lt/documents/20184/3686852/LNK-LOGO-HD.png","url":"https://live.lnk.lt/lnk_live/lnk/playlist.m3u8?tokenstarttime=0\u0026tokenendtime=1567224902\u0026tokenhash=_HpTyI7gllqpaAYr5edPhM9eJpSFa8-MU-DFA2pDBwIn1L9pPEzDEy1qhfb6459jNk5MsBIUhtK3Sj7hdAt5-A=="},{"title":"Lietuvos rytas HD","picture":"https://www.telia.lt/documents/20184/3686852/LRYTAS+TV+LOGOTIPAS.png","url":"https://ssb-live.lrytas.lt/live/smil:lrytas.smil/playlist.m3u8?tokenhash=4OO6OT-crEbXN8LW68hcNHeEdLqxWi5bacQDHFiL-FZIKziXaZfImJYHRUWKumQoh5MBOdqhKIR14bxMe_Z9xQ==\u0026tokenendtime=1567275300"},{"title":"LRT HD","picture":"https://www.telia.lt/documents/20184/3686852/LRT_262x262.png","url":"https://srautas.lrt.lt/lrt_televizija/smil:lrt_televizija.smil/playlist.m3u8?tokenhash=I87Q3WncyOyWUoApDlooGKDOSl5tZA3ZoZxsKUbhR9K_ExFZJI5Fak7mWe87PxmB-47Lc79qe8FgkAWzf-jjDA==\u0026tokenendtime=1567189923"}][erikas@ISP livetv]
```

Issaugok ir regeneruok once again:
```
cd /opt/livetv && ./livetv generate
```

**Comment by erkexzcx** [comment]
Gal tu uzsienyje gyveni? Gali but, kad ir del to nekrauna.

**Comment by bencius** [comment]
Vilnius - Lietuva. http://starproject.lt/LT_TV.php va mano failas, gali checkint :)

**Comment by bencius** [comment]
Galimai, gal as neteisingai chown padariau ir del to pjauna gryba?

**Comment by erkexzcx** [comment]
Hmmm, man regis žinau kas gali būti - bandai žiūrėti ne iš to (public) IP, iš kurio mėgini žiūrėti TV. Pas mane namie ODROID XU4 dirba ir tiek aš, tiek ODROID'as po tuo pačiu public IP ir dėl to krauna. Daugiau nežinau kas gali būt, nes man kai numetei tą savo url į PHP failą tai visiem linkam `403` meta.

**Comment by bencius** [comment]
Teisingas variantas. Taip as uzsikuriau ant remote, ir taip, pamirsau, kad TokenHash generuoja tam IP :) Geras pastebejimas, rekomenduociau tai pamineti readme.

**Comment by bencius** [comment]
Ir sita siulyciau dadet :) 

`func generateLTV2() {
	ltv2URL, err := downloadContent("https://www.lrt.lt/servisai/stream_url/live/get_live_url.php?channel=LTV2")
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}

	var result map[string]interface{}
	json.Unmarshal([]byte(ltv2URL), &result)
	level1 := result["response"].(map[string]interface{})
	level2 := level1["data"].(map[string]interface{})
	url := fmt.Sprintf("%v", level2["content"])

	addEntry("LRT Plius HD", "https://www.telia.lt/medias/tv-logo-lrt-plius-hd.png?context=bWFzdGVyfGZja0ltYWdlfDc5NDF8aW1hZ2UvcG5nfGZja0ltYWdlL2hlNy9oOTQvODkzMDc3OTY5MzA4Ni5wbmd8MWNkM2RmOTBlZDc4Yzg0MjFjZWIyZDU3NjQ2N2Y5MzdmMDg3YjQ0MmJlYWNiODEwOWQ5YjQyOTRkM2Q3YjI3Zg", url)
}`

**Comment by erkexzcx** [comment]
All done. Check :)
