### ISSUE TITLE
Iš linux pakuojant su UPX macOS binarikai neveikia.

### ISSUE THREAD

**Issue by sabakinaz** [erkexzcx/lietuviska-tv#10]
Va ką gaunam:
./lietuviskatv_darwin_x86_64
Killed: 9

Susiję:
[1](https://github.com/upx/upx/issues/222)
[2](https://github.com/upx/upx/issues/187)

Siūlymas arba naudoti UPX iš devel brancho, arba nespausti macOS binarikų.

**Comment by erkexzcx** [comment]
Čia mano providinami binaries, ar tavo paties suspaustas?

**Comment by sabakinaz** [comment]
Tavo. Jeigu kompiliuoju iš sourco ir spaudžiu su UPX tiesiai iš macOS - viskas veikia.

**Comment by erkexzcx** [comment]
Paconfirmink, ar veikia necompressintas binary (įdėjau į zip, nes neleidžia čia įkelt):

[lietuviskatv_darwin_x86_64.zip](https://github.com/erkexzcx/lietuviska-tv/files/3960379/lietuviskatv_darwin_x86_64.zip)

**Comment by sabakinaz** [comment]
Veikia:
./lietuviskatv_darwin_x86_64
2019/12/13 12:55:48 Starting...
2019/12/13 12:55:48 Started!

**Comment by erkexzcx** [comment]
All done. https://github.com/erkexzcx/lietuviska-tv/releases/latest
