### ISSUE TITLE
Technicolor TG389ac

### ISSUE THREAD

**Issue by malonumas** [erkexzcx/lietuviska-tv#11]
Sveiki! Turiu viena pastebejima. Paleidus skripta Telios Technicolor TG389ac vidiniame tinkle, viskas veikia tik tame kompiuteryje kur paleidi skripta, is kitu kompiuteriu ir prietaisu neina neina prisijungti. Kai wan forwardini i lan, tada viskas puikiai veikia, tik su isoriniu ip. Kituose tinkluose viskas gerai veikia vidiniam tinkle.

**Comment by erkexzcx** [comment]
Sveikas. Esu 100% tikras, kad tai ne programos problema, o tinklo konfiguracijos arba host'o firewall'o bėda.

> Paleidus skripta Telios Technicolor TG389ac vidiniame tinkle...

Ant ko paleidus? Gal firewall neatidarei? Surašyk daugiau detalių (ant ko, koks device, kokie ir kiek tinklų) - gal rasim išeitį. ;)

**Comment by malonumas** [comment]
Leidau ant ubuntu 18.04 ir 19.10. firewall nera. Greiciausiai cia telia kazko prichimicinus. Nes su kitu routeriu puikiai veikia :)

**Comment by malonumas** [comment]
tinklo kauke vienam buvo netokia nurodyta. Atsiprasau uz sutrugdyma ;)

**Comment by erkexzcx** [comment]
Hah :D Awesome, kad pavyko!
