### ISSUE TITLE
VLC Garsas

### ISSUE THREAD

**Issue by lapiux** [erkexzcx/lietuviska-tv#12]
Sveiki, VLC rodo vaizda bet negroja garso, koki patarimai butu?

**Comment by erkexzcx** [comment]
Sveiks. Koks kanalas?

**Comment by lapiux** [comment]
Sveikas, visi kanalai be garso

**Comment by erkexzcx** [comment]
Ką tik pacheckinau - viskas veikia. Pasižiūrėk eilės tvarka:
1. Gal VLC labai sena versija?
2. Gal užsimūtinęs garsą? :D
3. Gal operacinėj sistemoj kažko trūksta, kad garso nėra?

Priedu, kokia OS (OS versija) ir kokia architektūra? Ir ar programa ką nors rašo output'e kai paleidi kanalą?

**Comment by lapiux** [comment]
Panasu kad bus nevykes projektas ir tiek,
Atnaujinau i pacia naujausia versija ir pora kanalu gavo garsa, bet po
kurio laiko prarado. tas pats TV3 per du skirtingus srautus rodo skirtingus
vaizdus... tik dabar vienas su garsu kitas be akivaizdziai vienas srautas
atsilieka

2019-12-20, pn, 23:14 Erikas <notifications@github.com> rašė:

**Comment by erkexzcx** [comment]
Panašu tai panašu :)
