### ISSUE TITLE
8989 portas naudojamas Sonarr

### ISSUE THREAD

**Issue by tasvaido** [erkexzcx/lietuviska-tv#15]
Naudoju Odroid serverį, taspats kaip raspberry pi, tik galingesnis. Jame pasikūręs visą media serverį - plex, sonarr, radarr, sabnzbd, torrents etc. Deja, portą 8989 naudoja Sonarr. Norėtųsi galimybės pasikeisti default portą iš 8989 į kokį kitą .

**Comment by erkexzcx** [comment]
Hey. Konfiguracijos porto pakeitimui nesu padaręs (bet ir nebūtų didelis darbas). Kai tik galėsiu padarysiu command line argumentą porto pakeitimui, na o dabar teks pasikeisti hardcodintą portą pačiam: https://github.com/erkexzcx/lietuviska-tv/blob/508a93671eef2fd7cbfce7eb5cefe1eba339eb0b/src/main.go#L45 (instrukcijos kaip susibuildinti yra pateikta README.md faile).

P.S. Naudoju ODROID XU4 kaip namų serveriuką:) Super device'as.

**Comment by erkexzcx** [comment]
https://github.com/erkexzcx/lietuviska-tv/releases/latest
