### ISSUE TITLE
EPG guide duplikuojasi/rodo info iš kitų kanalų

### ISSUE THREAD

**Issue by erkexzcx** [erkexzcx/lietuviska-tv#2]
Kažkas negerai su m3u playlist generavimu. Niekaip nerandu kas negerai, bet turiu nuojautą kad čia arba HTTP serveris kažkaip negerai servina linkus arba Kodi Simple IPTV pluginas susifuckupina pamatęs tokio ilgumo M3U8 linką ir nebesupranta kur EPG o kur TV link.

Reik investiguot, bet aš neberandu kur problema gali būt.

**Comment by justnojus5** [comment]
https://www.lrt.lt/servisai/stream_url/live/get_live_url.php?channel=LTV1 Nuoroda nieko nerodo

**Comment by erkexzcx** [comment]
Galėsiu pažiūrėt vakare. Greičiausiai perrašysiu kodą, kad nereiktų nieko daryt (tiesiog paleidi executable ir naudojiesi - simple as that). Nebereikės php ir web serverio, tik mano executable.

**Comment by erkexzcx** [comment]
https://github.com/erkexzcx/lietuviska-tv#troubleshooting matei tikiuosi? :) Bet vakare vistiek pažiūrėsiu.

**Comment by justnojus5** [comment]
Aš naudoju kanalus ant Android telefono, tai executable neveiks (Tik ant Windows'u)

**Comment by erkexzcx** [comment]
O tu ant Windowsu pasileides sita executable buvai ar kaip?

**Comment by justnojus5** [comment]
Aš išvis ant windows'u niekada neleidau. Aš ant Andriod leidau kanalus

**Comment by erkexzcx** [comment]
O ar galėtum paaiškinti kuom šis mano github projektas susijęs su tavo per Android žiūrimais kanalais?

**Comment by justnojus5** [comment]
Nes, instrukcijoje radau nuorodas į LNK TV3 Info TV ir t.t ir naudoju.

**Comment by erkexzcx** [comment]
Tai kuom susijęs https://github.com/erkexzcx/lietuviska-tv/issues/2#issuecomment-536284564 su šiuo projektu? O be to, tas URL rodo.

**Comment by justnojus5** [comment]
LRT nuoroda neatsidaro per VLC. O dėl Windows'u sakiau kad executable pasileidžia, bet pats nebandžiau jo paleist

**Comment by erkexzcx** [comment]
Dabar gerai?

**Comment by erkexzcx** [comment]
Not relevant issue TBH.
