### ISSUE TITLE
Mips targetas openwrt su eglibc vietoj ucglibc

### ISSUE THREAD

**Issue by allstone** [erkexzcx/lietuviska-tv#3]
Gal atliekant release MIPS compiler galima butu nustatyti targeta su eglibc vietoj ucglibc - tada executable butu tam paciam MIPS cpu skirtas, taciau naudotu eglibc ir veiktu OpenWRT routeriuose.

Info radau cia: https://github.com/GeertJohan/openwrt-go/issues/2
Kazkiek info kodel eglibc reik: http://sgros.blogspot.com/2014/05/uclibc-versus-eglibc.html

**Comment by erkexzcx** [comment]
Impressive - pasileisti mano scripta ant routerio yra next level shit :D Pažiūrėsiu vakare, na o jei skubos tvarka - atsisiusk mano projekta, paeditink `build.sh` scripta ir paziurek ka gali paeditinti, kad veiktu.

**Comment by allstone** [comment]
Ah, lets see.. Perziurejau https://gist.github.com/asukakenji/f15ba7e588ac42795f421b48b8aede63 kazkaip turiu itarima, kad pakeisti liba reiktu pasibuildint savo go compileri? Hm, su go neteko susidurti, kazin tai vienintele iseitis, ar kazkur yra dokumentuoti tie targetai?

**Comment by allstone** [comment]
ok, kol kas manau, kad reiktu mipsle targeto su soft floating points FPU. Tai reiktu prieti  GOMIPS=softfloat  ir turetu suveikti.

**Comment by erkexzcx** [comment]
Žodžiu šiek tiek apsivaliau platformas ir jokių mips platformų nesupportinsiu. You are on your own. README.md parašiau kas kur ir kaip :)
