### ISSUE TITLE
Sąraše nėra LNK

### ISSUE THREAD

**Issue by justnojus5** [erkexzcx/lietuviska-tv#6]
Kur dingo LNK? Anksčiau buvo, dabar nėra

**Comment by erkexzcx** [comment]
Hi. Matei https://github.com/erkexzcx/lietuviska-tv/blob/master/README.md ("nerodo LNK")? Palauk iki kol pradės rodyti tiesioginę transliaciją kurios nors LNK laidos - tada atsiras. Jei viestiek ne - let me know. Gal pasikete pas juos sistemoje kažkas ir scriptas nenuparsina (turėtų ir InfoTV nerodyti kartu jei taip).

**Comment by justnojus5** [comment]
Info TV visada rodo

**Comment by erkexzcx** [comment]
Va ką turėjau omeny:
> LNK rodo tokiu principu - kai kuriuo nors metu per LNK GO rodo kokią nors tiesioginią transliaciją, scriptas tuo metu gali nuparsinti M3U8 nuorodą per kurią galima žiūrėti LNK TV. Kai transliacija baigiasi - nuorodos nebelieka, tačiau scriptas iš atminties išsitraukia paskutinę galimą nuorodą kuri dažniausiai veikia iki kitos dienos pietų.

**Comment by justnojus5** [comment]
Aišku
