### ISSUE TITLE
strings.replaceAll(..) neegzistuoja senesnėse Go versijose

### ISSUE THREAD

**Issue by ist-dev** [erkexzcx/lietuviska-tv#9]
Senesnės Golang versijos nepalaiko strings.replaceAll(...). Dažnai linux distribucijų repo defaultinis go nėra pats naujausias. Internete randu, šio metodo nepalaiko minimum iki golang 1.11.

Pakeiskite **proxy.go** faile:
`
99: 			line = strings.ReplaceAll(line, "URI=\"", "URI=\""+"http://"+r.Host+"/iptv/"+encodedChannelName+"/")
`
į eilutę
`
99:			line = strings.Replace(line, "URI=\"", "URI=\""+"http://"+r.Host+"/iptv/"+encodedChannelName+"/", -1)
`

Tuomet projektas kompiliuosis ir ant senesnių golang versijų.

Testuota:
x86_64, Ubuntu 18.04 LTS, golang 1.10
arm RPI3 (debian 9) Linux (OSMC kodi media center), golang  1.7

**Comment by erkexzcx** [comment]
Official repos turi seną (ir **labai** seną) Golang versiją. Pagal šitas instrukcijas įsidiek naujausią: https://www.digitalocean.com/community/tutorials/how-to-install-go-on-debian-9

O šeip nesupportinsiu senų versijų, nes tam nėra tikslo.

**Comment by erkexzcx** [comment]
https://github.com/erkexzcx/lietuviska-tv/blob/master/README.md#tr%C5%ABksta-norimos-platformos-irar-architekt%C5%ABros atnaujinau :)
